### ISSUE TITLE
Crash after update to latest code

### ISSUE THREAD

**Issue by IanSmallshire** [happycube/ld-decode#357]
`ian@ian-ddd230:~/github/ld-decode$ python3 -u ld-decode.py /media/ian/LDS/GrangeHill_CAV_PAL_side1_2019-09-07_15-52-53.lds /media/ian/LDS/GrangeHill_CAV_PAL_side1_2019-09-07_15-52-53 --pal -s 0 2>&1 | tee /media/ian/LDS/GrangeHill_CAV_PAL_side1_2019-09-07_15-52-53.log  ERROR - please paste the following into a bug report:
current sample: 0
arguments: Namespace(MTF=None, MTF_offset=None, daa=False, ignoreleadout=False, infile='/media/ian/LDS/GrangeHill_CAV_PAL_side1_2019-09-07_15-52-53.lds', inputfreq=None, length=110000, nodod=False, noefm=False, ntsc=False, ntscj=False, outfile='/media/ian/LDS/GrangeHill_CAV_PAL_side1_2019-09-07_15-52-53', pal=True, seek=-1, start=0, threads=5, vbpf_high=None, verboseVITS=False, vlpf=None)
Exception: index 65453 is out of bounds for axis 0 with size 65406  Traceback:
  File "ld-decode.py", line 109, in <module>
    f = ldd.readfield()
  File "/home/ian/github/ld-decode/lddecode_core.py", line 2466, in readfield
    f, offset = self.decodefield(initphase = initphase)
  File "/home/ian/github/ld-decode/lddecode_core.py", line 2438, in decodefield
    self.rawdecode = self.demodcache.read(self.readloc, self.readlen, self.mtf_level)
  File "/home/ian/github/ld-decode/lddecode_core.py", line 923, in read
    rv['audio'] = self.rf.audio_phase2(rv['audio'])
  File "/home/ian/github/ld-decode/lddecode_core.py", line 582, in audio_phase2
    field_audio = self.audio_dropout_detector(field_audio)
  File "/home/ian/github/ld-decode/lddecode_core.py", line 536, in audio_dropout_detector
    field_audio_dod[channel][0:ra[1]] = field_audio_dod[channel][ra[1]+1]
Traceback (most recent call last):
  File "ld-decode.py", line 109, in <module>
    f = ldd.readfield()
  File "/home/ian/github/ld-decode/lddecode_core.py", line 2466, in readfield
    f, offset = self.decodefield(initphase = initphase)
  File "/home/ian/github/ld-decode/lddecode_core.py", line 2438, in decodefield
    self.rawdecode = self.demodcache.read(self.readloc, self.readlen, self.mtf_level)
  File "/home/ian/github/ld-decode/lddecode_core.py", line 923, in read
    rv['audio'] = self.rf.audio_phase2(rv['audio'])
  File "/home/ian/github/ld-decode/lddecode_core.py", line 582, in audio_phase2
    field_audio = self.audio_dropout_detector(field_audio)
  File "/home/ian/github/ld-decode/lddecode_core.py", line 536, in audio_dropout_detector
    field_audio_dod[channel][0:ra[1]] = field_audio_dod[channel][ra[1]+1]
IndexError: index 65453 is out of bounds for axis 0 with size 65406

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "ld-decode.py", line 121, in <module>
    write_json(ldd, outname)
  File "ld-decode.py", line 96, in write_json
    jsondict = ldd.build_json(ldd.curfield)
  File "/home/ian/github/ld-decode/lddecode_core.py", line 2862, in build_json
    vp['isSourcePal'] = True if f.rf.system == 'PAL' else False
AttributeError: 'NoneType' object has no attribute 'rf'
`

**Comment by happycube** [comment]
fixed
