### ISSUE TITLE
Compilation and installation of ld-decode-tools under Ubuntu 21.10

### ISSUE THREAD

**Issue by simoninns** [happycube/ld-decode#668]
This issue is for notes and issues when compiling and installing under 21.10 since I had a fresh install to test from:

From the installation instructions on the wiki:

Remove qt5-default package from sudo apt install

# Error 1
make -j8 all
cc -O2 -Wno-deprecated-declarations -o ld-ldf-reader ld-ldf-reader.c -lavcodec -lavutil -lavformat
python3 setup.py build
cd tools && qmake -recursive PREFIX="/usr/local" BRANCH="master" COMMIT="78aa57c"
/bin/sh: 1: qmake: not found
make: *** [Makefile:67: build-tools] Error 127
make: *** Waiting for unfinished jobs....

## Solution
sudo apt install qt5-qmake

# Error 2
Project ERROR: Unknown module(s) in QT: core gui widgets

## Solution
apt install libqt5charts5-dev

this pulls in the right files... but I don't think it has anything to do with the charts lib itself?  Need to investigate exactly what was missing.

**Comment by simoninns** [comment]
Some build warnings from Qt whilst compiling (compilation was successful):

g++ -Wl,-O1 -o ld-chroma-encoder main.o palencoder.o lddecodemetadata.o logging.o vbidecoder.o dropouts.o   /usr/lib/x86_64-linux-gnu/libQt5Core.so -lpthread   
In member function ‘void QVector<T>::append(const T&) [with T = Frame]’,
    inlined from ‘void DiscMap::addPadding(qint32, qint32)’ at discmap.cpp:641:24:
cc1plus: warning: writing 1 byte into a region of size 0 [-Wstringop-overflow=]
In file included from /usr/include/x86_64-linux-gnu/qt5/QtCore/qbytearray.h:46,
                 from /usr/include/x86_64-linux-gnu/qt5/QtCore/qstring.h:50,
                 from /usr/include/x86_64-linux-gnu/qt5/QtCore/qcoreapplication.h:44,
                 from /usr/include/x86_64-linux-gnu/qt5/QtCore/QCoreApplication:1,
                 from discmap.h:28,
                 from discmap.cpp:25:
/usr/include/x86_64-linux-gnu/qt5/QtCore/qarraydata.h: In member function ‘void DiscMap::addPadding(qint32, qint32)’:
/usr/include/x86_64-linux-gnu/qt5/QtCore/qarraydata.h:129:8: note: at offset 24 into destination object ‘QTypedArrayData<Frame>::<anonymous>’ of size 24
  129 | struct QTypedArrayData
      |        ^~~~~~~~~~~~~~~
In member function ‘void QVector<T>::append(const T&) [with T = Frame]’,
    inlined from ‘void DiscMap::addPadding(qint32, qint32)’ at discmap.cpp:641:24:
cc1plus: warning: writing 1 byte into a region of size 0 [-Wstringop-overflow=]
/usr/include/x86_64-linux-gnu/qt5/QtCore/qarraydata.h: In member function ‘void DiscMap::addPadding(qint32, qint32)’:
/usr/include/x86_64-linux-gnu/qt5/QtCore/qarraydata.h:129:8: note: at offset [25, 49] into destination object ‘QTypedArrayData<Frame>::<anonymous>’ of size 24
  129 | struct QTypedArrayData
      |        ^~~~~~~~~~~~~~~

**Comment by simoninns** [comment]
Running ld-decode results in:

sdi@sehoapollo01:~/github/ld-decode$ ld-decode
Traceback (most recent call last):
  File "/usr/local/bin/ld-decode", line 4, in <module>
    __import__('pkg_resources').run_script('ld-decode==7', 'ld-decode')
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 651, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 1455, in run_script
    exec(script_code, namespace, namespace)
  File "/usr/local/lib/python3.9/dist-packages/ld_decode-7-py3.9.egg/EGG-INFO/scripts/ld-decode", line 9, in <module>
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 664, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 627, in _load_backward_compatible
  File "<frozen zipimport>", line 259, in load_module
  File "/usr/local/lib/python3.9/dist-packages/ld_decode-7-py3.9.egg/lddecode/audio.py", line 25, in <module>
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 664, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 627, in _load_backward_compatible
  File "<frozen zipimport>", line 259, in load_module
  File "/usr/local/lib/python3.9/dist-packages/ld_decode-7-py3.9.egg/lddecode/core.py", line 32, in <module>
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 664, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 627, in _load_backward_compatible
  File "<frozen zipimport>", line 259, in load_module
  File "/usr/local/lib/python3.9/dist-packages/ld_decode-7-py3.9.egg/lddecode/utils.py", line 24, in <module>
  File "/usr/lib/python3/dist-packages/numba/core/decorators.py", line 214, in wrapper
    disp.enable_caching()
  File "/usr/lib/python3/dist-packages/numba/core/dispatcher.py", line 781, in enable_caching
    self._cache = FunctionCache(self.py_func)
  File "/usr/lib/python3/dist-packages/numba/core/caching.py", line 616, in __init__
    self._impl = self._impl_class(py_func)
  File "/usr/lib/python3/dist-packages/numba/core/caching.py", line 351, in __init__
    raise RuntimeError("cannot cache function %r: no locator available "
RuntimeError: cannot cache function 'scale': no locator available for file '/usr/local/lib/python3.9/dist-packages/ld_decode-7-py3.9.egg/lddecode/utils.py'

**Comment by simoninns** [comment]
Installation of qt-creator also fails to load IDE.  Missing library:

sudo apt install libopengl0

(this is when installing Qt Creator from the official installation tool).

**Comment by simoninns** [comment]
Removed ld-decode related comments and moved to issue #671

**Comment by simoninns** [comment]
Closing this... better to test with 22.04 LTS
